name: Continuous Integration
on: push
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
          check-latest: true
      - name: Install modules
        run: npm i
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: current
          path: .
  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: current
      - name: Run tests
        run: npm run test
