name: Automated Testing
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Load code
        uses: actions/checkout@v2
      - name: Prepare environment
        uses: actions/setup-node@v2
        with:
          node-version: "15"
          check-latest: true
      - name: Install modules
        run: npm i
      - name: Run tests
        run: npm run test
